# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\ModTools\ModOrganizer\plugins\data\mergewizard\build\ui\widgets\ActionWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ActionWidget(object):
    def setupUi(self, ActionWidget):
        ActionWidget.setObjectName("ActionWidget")
        ActionWidget.resize(640, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(ActionWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(ActionWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.logGroup = QtWidgets.QGroupBox(self.splitter)
        self.logGroup.setObjectName("logGroup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.logGroup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.logView = QtWidgets.QTableView(self.logGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logView.sizePolicy().hasHeightForWidth())
        self.logView.setSizePolicy(sizePolicy)
        self.logView.setMinimumSize(QtCore.QSize(0, 200))
        self.logView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.logView.setProperty("showDropIndicator", False)
        self.logView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.logView.setObjectName("logView")
        self.logView.horizontalHeader().setDefaultSectionSize(100)
        self.logView.horizontalHeader().setMinimumSectionSize(18)
        self.logView.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_3.addWidget(self.logView, 0, 0, 1, 1)
        self.actionGroup = QtWidgets.QGroupBox(self.splitter)
        self.actionGroup.setObjectName("actionGroup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.actionGroup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.actionView = QtWidgets.QTableView(self.actionGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionView.sizePolicy().hasHeightForWidth())
        self.actionView.setSizePolicy(sizePolicy)
        self.actionView.setMinimumSize(QtCore.QSize(0, 200))
        self.actionView.setProperty("showDropIndicator", False)
        self.actionView.setObjectName("actionView")
        self.actionView.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.actionView)
        self.applyButton = QtWidgets.QPushButton(self.actionGroup)
        self.applyButton.setObjectName("applyButton")
        self.verticalLayout_2.addWidget(self.applyButton)
        self.verticalLayout.addWidget(self.splitter)

        self.retranslateUi(ActionWidget)
        QtCore.QMetaObject.connectSlotsByName(ActionWidget)

    def retranslateUi(self, ActionWidget):
        _translate = QtCore.QCoreApplication.translate
        ActionWidget.setWindowTitle(_translate("ActionWidget", "Form"))
        self.logGroup.setTitle(_translate("ActionWidget", "Log"))
        self.actionGroup.setTitle(_translate("ActionWidget", "Actions"))
        self.applyButton.setText(_translate("ActionWidget", "Apply Actions"))
