# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\ModTools\ModOrganizer\plugins\data\mergewizard\build\ui\widgets\MergeConfigWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MergeConfigWidget(object):
    def setupUi(self, MergeConfigWidget):
        MergeConfigWidget.setObjectName("MergeConfigWidget")
        MergeConfigWidget.resize(640, 480)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(MergeConfigWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(MergeConfigWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.zMergeBox = QtWidgets.QGroupBox(self.splitter)
        self.zMergeBox.setObjectName("zMergeBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.zMergeBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.zMergeView = QtWidgets.QTreeView(self.zMergeBox)
        self.zMergeView.setMouseTracking(True)
        self.zMergeView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.zMergeView.setUniformRowHeights(True)
        self.zMergeView.setObjectName("zMergeView")
        self.zMergeView.header().setMinimumSectionSize(1)
        self.zMergeView.header().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.zMergeView)
        self.originalBox = QtWidgets.QGroupBox(self.splitter)
        self.originalBox.setObjectName("originalBox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.originalBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.originalView = QtWidgets.QTreeView(self.originalBox)
        self.originalView.setMouseTracking(True)
        self.originalView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.originalView.setUniformRowHeights(True)
        self.originalView.setObjectName("originalView")
        self.originalView.header().setMinimumSectionSize(1)
        self.originalView.header().setStretchLastSection(False)
        self.verticalLayout_9.addWidget(self.originalView)
        self.verticalLayout_2.addWidget(self.splitter)

        self.retranslateUi(MergeConfigWidget)
        QtCore.QMetaObject.connectSlotsByName(MergeConfigWidget)

    def retranslateUi(self, MergeConfigWidget):
        _translate = QtCore.QCoreApplication.translate
        MergeConfigWidget.setWindowTitle(_translate("MergeConfigWidget", "Form"))
        self.zMergeBox.setTitle(_translate("MergeConfigWidget", "Merge Configuration"))
        self.originalBox.setTitle(_translate("MergeConfigWidget", "Original"))
