# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\ModTools\ModOrganizer\plugins\data\mergewizard\build\ui\widgets\MergeSelectWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MergeSelectWidget(object):
    def setupUi(self, MergeSelectWidget):
        MergeSelectWidget.setObjectName("MergeSelectWidget")
        MergeSelectWidget.resize(640, 480)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(MergeSelectWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(MergeSelectWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mergeView = QtWidgets.QTreeView(self.groupBox)
        self.mergeView.setObjectName("mergeView")
        self.mergeView.header().setMinimumSectionSize(26)
        self.verticalLayout.addWidget(self.mergeView)
        self.progressFrame = QtWidgets.QFrame(self.groupBox)
        self.progressFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progressFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progressFrame.setObjectName("progressFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.progressFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addWidget(self.progressFrame)
        self.frame_2 = QtWidgets.QFrame(self.groupBox)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sortByPriority = QtWidgets.QCheckBox(self.frame_2)
        self.sortByPriority.setChecked(True)
        self.sortByPriority.setObjectName("sortByPriority")
        self.horizontalLayout_2.addWidget(self.sortByPriority)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.selectedMerge = QtWidgets.QLineEdit(self.frame_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.selectedMerge.setPalette(palette)
        self.selectedMerge.setReadOnly(True)
        self.selectedMerge.setObjectName("selectedMerge")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.selectedMerge)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.frame_2)
        self.selectMergeButton = QtWidgets.QPushButton(self.groupBox)
        self.selectMergeButton.setObjectName("selectMergeButton")
        self.verticalLayout.addWidget(self.selectMergeButton)
        self.verticalLayout_2.addWidget(self.groupBox)

        self.retranslateUi(MergeSelectWidget)
        QtCore.QMetaObject.connectSlotsByName(MergeSelectWidget)

    def retranslateUi(self, MergeSelectWidget):
        _translate = QtCore.QCoreApplication.translate
        MergeSelectWidget.setWindowTitle(_translate("MergeSelectWidget", "Form"))
        self.groupBox.setTitle(_translate("MergeSelectWidget", "Merges"))
        self.sortByPriority.setText(_translate("MergeSelectWidget", "Sort plugins by position"))
        self.label.setText(_translate("MergeSelectWidget", "Selected Merge:"))
        self.selectMergeButton.setText(_translate("MergeSelectWidget", "Select Plugins from Merge"))
