# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\ModTools\ModOrganizer\plugins\data\mergewizard\build\ui\widgets\PluginInfoWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PluginInfoWidget(object):
    def setupUi(self, PluginInfoWidget):
        PluginInfoWidget.setObjectName("PluginInfoWidget")
        PluginInfoWidget.resize(856, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(PluginInfoWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(PluginInfoWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.infoView = QtWidgets.QTableView(self.groupBox)
        self.infoView.setWordWrap(False)
        self.infoView.setObjectName("infoView")
        self.infoView.horizontalHeader().setStretchLastSection(True)
        self.infoView.verticalHeader().setDefaultSectionSize(23)
        self.gridLayout.addWidget(self.infoView, 0, 0, 1, 3)
        self.indirectCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.indirectCheckBox.setChecked(True)
        self.indirectCheckBox.setObjectName("indirectCheckBox")
        self.gridLayout.addWidget(self.indirectCheckBox, 1, 0, 1, 1)
        self.sortCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.sortCheckBox.setChecked(True)
        self.sortCheckBox.setObjectName("sortCheckBox")
        self.gridLayout.addWidget(self.sortCheckBox, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(549, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(PluginInfoWidget)
        QtCore.QMetaObject.connectSlotsByName(PluginInfoWidget)

    def retranslateUi(self, PluginInfoWidget):
        _translate = QtCore.QCoreApplication.translate
        PluginInfoWidget.setWindowTitle(_translate("PluginInfoWidget", "Form"))
        self.groupBox.setTitle(_translate("PluginInfoWidget", "Plugin Info"))
        self.indirectCheckBox.setText(_translate("PluginInfoWidget", "Include indirect relationships"))
        self.sortCheckBox.setText(_translate("PluginInfoWidget", "Sort by priority"))
