# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\ModTools\ModOrganizer\plugins\data\mergewizard\build\ui\widgets\PluginTextWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PluginTextWidget(object):
    def setupUi(self, PluginTextWidget):
        PluginTextWidget.setObjectName("PluginTextWidget")
        PluginTextWidget.resize(290, 239)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PluginTextWidget.sizePolicy().hasHeightForWidth())
        PluginTextWidget.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(PluginTextWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(PluginTextWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.edit = TextStatusEditComplete(self.groupBox)
        self.edit.setObjectName("edit")
        self.verticalLayout.addWidget(self.edit)
        self.button = QtWidgets.QPushButton(self.groupBox)
        self.button.setObjectName("button")
        self.verticalLayout.addWidget(self.button)
        self.verticalLayout_2.addWidget(self.groupBox)

        self.retranslateUi(PluginTextWidget)
        QtCore.QMetaObject.connectSlotsByName(PluginTextWidget)

    def retranslateUi(self, PluginTextWidget):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox.setTitle(_translate("PluginTextWidget", "Type or Paste Plugin Names (one name per line)"))
        self.button.setText(_translate("PluginTextWidget", "Add to Selection"))
from mergewizard.widgets.TextStatusEditComplete import TextStatusEditComplete
