# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\ModTools\ModOrganizer\plugins\data\mergewizard\build\ui\dialogs\MergeSelectDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MergeSelectDialog(object):
    def setupUi(self, MergeSelectDialog):
        MergeSelectDialog.setObjectName("MergeSelectDialog")
        MergeSelectDialog.resize(572, 436)
        self.gridLayout = QtWidgets.QGridLayout(MergeSelectDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.mergeView = QtWidgets.QTreeView(MergeSelectDialog)
        self.mergeView.setObjectName("mergeView")
        self.gridLayout.addWidget(self.mergeView, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(MergeSelectDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(MergeSelectDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sortByPriority = QtWidgets.QCheckBox(self.frame)
        self.sortByPriority.setChecked(True)
        self.sortByPriority.setObjectName("sortByPriority")
        self.horizontalLayout_2.addWidget(self.sortByPriority)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.selectedMerge = QtWidgets.QLineEdit(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.selectedMerge.setPalette(palette)
        self.selectedMerge.setReadOnly(True)
        self.selectedMerge.setObjectName("selectedMerge")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.selectedMerge)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.progressFrame = QtWidgets.QFrame(MergeSelectDialog)
        self.progressFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progressFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progressFrame.setObjectName("progressFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.progressFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressLayout = QtWidgets.QFormLayout()
        self.progressLayout.setObjectName("progressLayout")
        self.progressLabel = QtWidgets.QLabel(self.progressFrame)
        self.progressLabel.setObjectName("progressLabel")
        self.progressLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.progressLabel)
        self.progressBar = QtWidgets.QProgressBar(self.progressFrame)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.progressLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.progressBar)
        self.horizontalLayout.addLayout(self.progressLayout)
        self.gridLayout.addWidget(self.progressFrame, 2, 0, 1, 1)
        self.label.setBuddy(self.selectedMerge)
        self.progressLabel.setBuddy(self.progressBar)

        self.retranslateUi(MergeSelectDialog)
        self.buttonBox.accepted.connect(MergeSelectDialog.accept)
        self.buttonBox.rejected.connect(MergeSelectDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(MergeSelectDialog)

    def retranslateUi(self, MergeSelectDialog):
        _translate = QtCore.QCoreApplication.translate
        MergeSelectDialog.setWindowTitle(_translate("MergeSelectDialog", "Dialog"))
        self.sortByPriority.setText(_translate("MergeSelectDialog", "Sort plugins by priority"))
        self.label.setText(_translate("MergeSelectDialog", "Selected Merge:"))
        self.progressLabel.setText(_translate("MergeSelectDialog", "Loading Merges: "))
