# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\ModTools\ModOrganizer\plugins\data\mergewizard\build\ui\dialogs\PageZMerge.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PageZMerge(object):
    def setupUi(self, PageZMerge):
        PageZMerge.setObjectName("PageZMerge")
        PageZMerge.resize(990, 698)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(PageZMerge)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.retranslateUi(PageZMerge)
        QtCore.QMetaObject.connectSlotsByName(PageZMerge)

    def retranslateUi(self, PageZMerge):
        _translate = QtCore.QCoreApplication.translate
        PageZMerge.setWindowTitle(_translate("PageZMerge", "WizardPage"))
        PageZMerge.setTitle(_translate("PageZMerge", "zMerge Configuration"))
        PageZMerge.setSubTitle(_translate("PageZMerge", "Create or modify a zMerge configuration for the selected plugins."))
