# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\ModTools\ModOrganizer\plugins\data\mergewizard\build\ui\dialogs\PageMergeSelect.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PageMergeSelect(object):
    def setupUi(self, PageMergeSelect):
        PageMergeSelect.setObjectName("PageMergeSelect")
        PageMergeSelect.resize(964, 649)
        self.verticalLayout = QtWidgets.QVBoxLayout(PageMergeSelect)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mergeView = QtWidgets.QTreeView(PageMergeSelect)
        self.mergeView.setObjectName("mergeView")
        self.verticalLayout.addWidget(self.mergeView)
        self.frame = QtWidgets.QFrame(PageMergeSelect)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sortByPriority = QtWidgets.QCheckBox(self.frame)
        self.sortByPriority.setChecked(True)
        self.sortByPriority.setObjectName("sortByPriority")
        self.horizontalLayout_2.addWidget(self.sortByPriority)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.selectedMerge = QtWidgets.QLineEdit(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.selectedMerge.setPalette(palette)
        self.selectedMerge.setReadOnly(True)
        self.selectedMerge.setObjectName("selectedMerge")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.selectedMerge)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.frame)
        self.progressFrame = QtWidgets.QFrame(PageMergeSelect)
        self.progressFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progressFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progressFrame.setObjectName("progressFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.progressFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressLayout = QtWidgets.QFormLayout()
        self.progressLayout.setObjectName("progressLayout")
        self.progressLabel = QtWidgets.QLabel(self.progressFrame)
        self.progressLabel.setObjectName("progressLabel")
        self.progressLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.progressLabel)
        self.progressBar = QtWidgets.QProgressBar(self.progressFrame)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.progressLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.progressBar)
        self.horizontalLayout.addLayout(self.progressLayout)
        self.verticalLayout.addWidget(self.progressFrame)
        self.label.setBuddy(self.selectedMerge)
        self.progressLabel.setBuddy(self.progressBar)

        self.retranslateUi(PageMergeSelect)
        QtCore.QMetaObject.connectSlotsByName(PageMergeSelect)

    def retranslateUi(self, PageMergeSelect):
        _translate = QtCore.QCoreApplication.translate
        PageMergeSelect.setWindowTitle(_translate("PageMergeSelect", "WizardPage"))
        PageMergeSelect.setTitle(_translate("PageMergeSelect", "Merge Selection"))
        PageMergeSelect.setSubTitle(_translate("PageMergeSelect", "Select an existing merge to initialize the list of selected plugins. The plugin\'s masters will be initialized with information from ModOrganizer rather than from the existing merge file."))
        self.sortByPriority.setText(_translate("PageMergeSelect", "Sort plugins by priority"))
        self.label.setText(_translate("PageMergeSelect", "Selected Merge:"))
        self.progressLabel.setText(_translate("PageMergeSelect", "Loading Merges: "))
